In [1]:
import pandas as pd
import numpy as np

In [2]:
df1 = pd.read_csv('finalplaylist1.csv',index_col=0)

In [3]:
df2 = pd.read_csv('finalplaylist2.csv',index_col=0)
df3 = pd.read_csv('finalplaylist3.csv',index_col=0)

In [4]:
df1.shape

(8133, 24)

In [5]:
df2.shape

(8962, 24)

In [6]:
df3.shape

(3759, 24)

In [7]:
df = pd.concat([df1,df2,df3],axis=0)


In [8]:
df.head()

name  duration  artist_name  is_explicit  \
id                                                                             
33xMbeHzmWd6Od0BmLZEUs                2K    152560  Nosaj Thing        False   
3UnyplmZaq547hwsfOR5yy   4 Billion Souls    197706    The Doors        False   
1w8QCSDH4QobcQeT4uMKLm  4 Minute Warning    244284    Radiohead        False   
7J9mBHG4J2eIfDAv5BehKA         7 Element    249939        Vitas        False   
1VZedwJj1gyi88WFRhfThb          #9 Dream    278320       R.E.M.        False   

                        time_signature  danceability  energy  key  loudness  \
id                                                                            
33xMbeHzmWd6Od0BmLZEUs               3         0.310   0.445    7   -13.355   
3UnyplmZaq547hwsfOR5yy               4         0.419   0.565    5   -11.565   
1w8QCSDH4QobcQeT4uMKLm               4         0.354   0.302    9   -13.078   
7J9mBHG4J2eIfDAv5BehKA               4         0.727   0.785    5    -6.707   
1VZedwJj1gyi88WFRhfThb               4         0.571   0.724    0    -5.967   

                        mode  ...  valence    tempo  popularity  Pop  Rock  \
id                            ...                                            
33xMbeHzmWd6Od0BmLZEUs     0  ...    0.122   95.360           0    0     1   
3UnyplmZaq547hwsfOR5yy     1  ...    0.648  151.277          25    0     1   
1w8QCSDH4QobcQeT4uMKLm     1  ...    0.223  123.753           1    0     1   
7J9mBHG4J2eIfDAv5BehKA     0  ...    0.960  129.649           0    0     0   
1VZedwJj1gyi88WFRhfThb     1  ...    0.385  116.755           6    1     1   

                        Hip Hop  Folk  Metal  Blues  Jazz  
id                                                         
33xMbeHzmWd6Od0BmLZEUs        0     0      0      0     0  
3UnyplmZaq547hwsfOR5yy        0     0      0      0     0  
1w8QCSDH4QobcQeT4uMKLm        0     1      0      0     0  
7J9mBHG4J2eIfDAv5BehKA        1     0      0      0     0  
1VZedwJj1gyi88WFRhfThb        0     0      0      0     0  

[5 rows x 24 columns]

In [9]:
df.shape

(20854, 24)

In [10]:
df.dropna(axis=0,how='any',inplace=True)

In [11]:
df.shape

(20852, 24)

In [12]:
df.drop_duplicates(subset=['name','artist_name'],inplace=True)

In [13]:
df.shape

(18833, 24)

In [14]:
df.columns

Index(['name', 'duration', 'artist_name', 'is_explicit', 'time_signature',
       'danceability', 'energy', 'key', 'loudness', 'mode', 'speechiness',
       'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo',
       'popularity', 'Pop', 'Rock', 'Hip Hop', 'Folk', 'Metal', 'Blues',
       'Jazz'],
      dtype='object')

In [15]:
indexNames = df[ (df['Pop'] == 0) & (df['Rock'] == 0) & (df['Hip Hop'] == 0) & (df['Folk'] == 0) & (df['Metal'] == 0) & (df['Blues'] == 0) & (df['Jazz'] == 0) ].index

In [16]:
indexNames

Index(['2YTRLoG5jdzCp4yg3B6OnH', '6Tq4LginUMBOgZrUs8M40h',
       '2vEkF5UazjaBL6CpG2BZgq', '7or26qS3BfpTtWO3BFw5GE',
       '3Vef8GlFWEzrP23UwHjWWl', '1Lwux3cAXrUG3UWjUEGteT',
       '2NsQgzcCEy9hZbHaBG4Xfy', '5pxUPHdS1ItmLjU25AbYLg',
       '5U7r8PAmvfILOMjmFeYlDL', '1LADUenCei27c26JD0pg05',
       ...
       '7x3vcsxOTWQm3FxRrUEqzv', '7uHRKSQ9WIlBBuBY7BHcbq',
       '6QlKONDgjp9JqcthAtDlKk', '60YDNopVT8FDOdtk0tWPNU',
       '0kT1yNCDeT6qLt2BgX1MdD', '6H7RUDjmjiGV4I9hE24Kk5',
       '7KvmojKwAts4vuuVS0TkB9', '0Z2D2EwQAdyz42Vhg4TUZ3',
       '1ZX0LUTVpuh8YzbQe7WbvU', '7AK01WpnqURCRFbOX4LOHa'],
      dtype='object', name='id', length=5961)

In [17]:
df.loc['6Tq4LginUMBOgZrUs8M40h']

name                143 (Kelly's song) 2011
duration                             266066
artist_name                Jake Shimabukuro
is_explicit                           False
time_signature                            4
danceability                           0.37
energy                                0.361
key                                       9
loudness                            -12.271
mode                                      1
speechiness                          0.0321
acousticness                           0.81
instrumentalness                       0.87
liveness                              0.113
valence                               0.479
tempo                                66.409
popularity                               20
Pop                                       0
Rock                                      0
Hip Hop                                   0
Folk                                      0
Metal                                     0
Blues                           

In [18]:
df.drop(indexNames , inplace=True)

In [53]:
df.to_csv('finalplaylist.csv')

In [19]:
df.shape

(12872, 24)

In [20]:
y = ['Pop', 'Rock', 'Hip Hop', 'Folk', 'Metal', 'Blues',
       'Jazz']

In [21]:
Y = df[y]

In [22]:
print(Y)

                        Pop  Rock  Hip Hop  Folk  Metal  Blues  Jazz
id                                                                  
33xMbeHzmWd6Od0BmLZEUs    0     1        0     0      0      0     0
3UnyplmZaq547hwsfOR5yy    0     1        0     0      0      0     0
1w8QCSDH4QobcQeT4uMKLm    0     1        0     1      0      0     0
7J9mBHG4J2eIfDAv5BehKA    0     0        1     0      0      0     0
1VZedwJj1gyi88WFRhfThb    1     1        0     0      0      0     0
...                     ...   ...      ...   ...    ...    ...   ...
21UkXrc9kD48rNpTMI2ecz    0     0        1     0      0      0     0
50a8bKqlwDEqeiEknrzkTO    0     0        1     0      0      0     0
4guBZjUyrGoHsTahO3IHdj    0     0        1     0      0      0     0
7niut1GcKrCVZe4mx7Tqp8    0     0        1     0      0      0     0
2BULAwmRpScmZE7YOF07e5    0     0        1     0      0      0     0

[12872 rows x 7 columns]


In [39]:
features = ['duration','is_explicit', 'time_signature',
       'danceability', 'energy', 'key', 'loudness', 'mode', 'speechiness',
       'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo',
       'popularity']

In [40]:
X = df[features]

In [41]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2,random_state = 0)

In [51]:
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=200)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train,y_train)

y_pred=clf.predict(X_test)

In [43]:
print(y_pred)

[[0 0 1 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 ...
 [1 0 1 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]]


In [28]:
y_test

Pop  Rock  Hip Hop  Folk  Metal  Blues  Jazz
id                                                                  
0qux2oJQ3lEWfGpKlGy47N    1     0        1     0      0      0     0
3ydI3CesHBnaY01Qff9jOr    0     1        0     0      0      0     0
0Hg2azrxVvQvmyh2S6qXCS    0     0        0     0      0      1     0
0ULm3rFCZSbIZcdFUOrgSm    1     1        0     0      0      0     0
13xM8Ik90iythL1dEt2Ihs    0     1        0     1      0      0     0
...                     ...   ...      ...   ...    ...    ...   ...
1vrXl5UJBWRJJxjCyCRPMv    1     1        0     0      0      0     0
098lPAWl2OmsCx64TXH5OQ    0     1        0     0      1      0     0
1ue7zm5TVVvmoQV8lK6K2H    1     0        0     0      0      0     0
7uYIX9O9DY6l1D3HiwHR1J    1     0        0     0      0      0     0
0Sbeihd75SGitymHS8Bqbh    1     0        0     0      0      0     0

[2575 rows x 7 columns]

In [52]:
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.32155339805825245
